/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ashwin' at '8/17/16 6:13 PM' with Gradle 2.13
 *
 * @author ashwin, @date 8/17/16 6:13 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
